# Generated by Django 3.0.6 on 2020-05-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='characters',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='created',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='edited',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='episode',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='planets',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='species',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='starships',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='vehicles',
            field=models.CharField(max_length=1000),
        ),
    ]
