# Generated by Django 3.0.6 on 2020-05-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_character_characterimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='autorizado',
        ),
        migrations.AddField(
            model_name='character',
            name='imagen',
            field=models.ManyToManyField(blank=True, related_name='r_imagen', to='films.CharacterImage', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='character',
            name='vehicles',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='films',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='starships',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
