# Generated by Django 3.0.6 on 2020-05-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_auto_20200531_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='episode',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
    ]
