# Generated by Django 3.0.6 on 2020-05-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_auto_20200531_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='character',
            name='created',
        ),
        migrations.RemoveField(
            model_name='character',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='character',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='films',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='height',
        ),
        migrations.RemoveField(
            model_name='character',
            name='homeworld',
        ),
        migrations.RemoveField(
            model_name='character',
            name='mass',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skin_color',
        ),
        migrations.RemoveField(
            model_name='character',
            name='species',
        ),
        migrations.RemoveField(
            model_name='character',
            name='starships',
        ),
        migrations.RemoveField(
            model_name='character',
            name='url',
        ),
        migrations.RemoveField(
            model_name='character',
            name='vehicles',
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
