# Generated by Django 3.0.6 on 2020-05-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_auto_20200531_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterimage',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='images', verbose_name='File'),
        ),
    ]
