# Generated by Django 3.0.6 on 2020-08-13 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='puntuacion',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
