# Generated by Django 3.0.6 on 2020-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_auto_20200813_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='score',
            field=models.ManyToManyField(blank=True, related_name='r_score', to='films.Score'),
        ),
    ]
