# Generated by Django 3.0.6 on 2020-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0021_auto_20200816_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
