# Generated by Django 3.0.6 on 2020-08-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0023_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='r_comment', to='films.Comment'),
        ),
    ]
