# Generated by Django 3.0.6 on 2020-05-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('episode', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('characters', models.CharField(max_length=100)),
                ('planets', models.CharField(max_length=100)),
                ('starships', models.CharField(max_length=100)),
                ('vehicles', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('created', models.CharField(max_length=100)),
                ('edited', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
