# Generated by Django 3.0.6 on 2020-05-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20200530_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
