# Generated by Django 3.0.6 on 2020-05-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20200530_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterimage',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='static/images', verbose_name='File'),
        ),
    ]
