# Generated by Django 3.0.6 on 2020-05-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_auto_20200531_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='film',
            name='created',
        ),
        migrations.RemoveField(
            model_name='film',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='film',
            name='planets',
        ),
        migrations.RemoveField(
            model_name='film',
            name='species',
        ),
        migrations.RemoveField(
            model_name='film',
            name='starships',
        ),
        migrations.RemoveField(
            model_name='film',
            name='url',
        ),
        migrations.RemoveField(
            model_name='film',
            name='vehicles',
        ),
    ]
