# Generated by Django 3.0.6 on 2020-05-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_auto_20200531_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
    ]
